#!/bin/bash
#
# findBox
#
# (c) Miguel Leitao, 2016
# Part of meoRemote: https://github.com/miguelleitao/meoRemote
#
# Scans network for available meoBoxes.
#
# Usage: ./findBox [-q] [-c] [NetMaskLenLimit [NetAddr]]
#     NetAddr defaults to addresses from all available net interfaces.
#     NetMaskLenLimit defaults to 24. Use 28 for a norrow (faster) search.
#     -q: quiet mode (no header)
#     -c: config file mode. Use ./findBox -c >appname.conf
#
mask2cdr ()
{
   local x=${1##*255.}
   set -- 0^^^128^192^224^240^248^252^254^ $(( (${#1} - ${#x})*2 )) ${x%%.*}
   x=${1%%$3*}
   echo $(( $2 + (${#x}/4) ))
}

cdr2mask ()
{
   set -- $(( 5 - ($1 / 8) )) 255 255 255 255 $(( (255 << (8 - ($1 % 8))) & 255 )) 0 0 0
   [ $1 -gt 1 ] && shift $1 || shift
   echo ${1-0}.${2-0}.${3-0}.${4-0}
}
masklen=24
if [ "$1" == "-q" ]; then
    quiet=1
    shift
fi
if [ "$1" == "-c" ]; then
    quiet=1
    conf=1
	#" |awk -c '{print \"box \" $5}"
    shift
fi
[ "$1" != "" ] && masklen=$1
[ "$quiet" != "1" ] && echo "# meoBoxes found:"
addrs=`ifconfig | grep  -e 'inet .*' |grep -v 127.0.0.1 |cut -f2 -dt |cut -d' ' -f2`
[ "$2" != "" ] && addrs=$2
#echo "adds: " $addrs
for i in $addrs; do
  #echo $i
  nmask=`ifconfig |grep inet |grep $i |cut -f3 -dt |cut -f2 -dk |cut -d' ' -f2`
  #echo "netmask: "$nmask
  min_cidr=`mask2cdr $nmask`
  #echo "min_cidr: "$min_cidr
  cidr=$(( $masklen > $min_cidr ? $masklen : $min_cidr ))
  #echo "cidr: "$cidr 
  nmask=`cdr2mask $cidr`
  IFS=. read -r ia1 ia2 ia3 ia4 <<< "$i"
  IFS=. read -r im1 im2 im3 im4 <<< "$nmask"
  naddr="$((ia1 & im1)).$((ia2 & im2)).$((ia3 & im3)).$((ia4 & im4))"
  #echo "netaddr:"$naddr
  if [ "$conf" != "1" ]; then
    nmap -n -p T:8082 -Pn --open -oG - $naddr/$cidr |grep open/tcp |cut -f2 -d' '
  else
    nmap -n -p T:8082 -Pn --open -oG - $naddr/$cidr |grep open/tcp |awk -c '{print "box " $2}'
  fi
done

