#!/bin/bash
echo "# meoBoxes found:"
addrs=`ifconfig | grep  -e 'inet .*: ' |grep -v 127.0.0.1 |cut -f2 -d: |cut -d' ' -f2`
for i in $addrs; do
  #echo $i
  nmap  -p T:8082 $i/28 |grep -B 4 open |grep report |cut -f5 -d' '
done
#nmap  -p T:8082 192.168.1.64/28 |grep -B 4 open |grep report |cut -f5 -d' '

